// Generated by https://quicktype.io

export interface PlacesResponse {
    type:        string;
    query:       string[];
    features:    Feature[];
    attribution: string;
}

export interface Feature {
    id:            string;
    type:          string;
    place_type:    string[];
    relevance:     number;
    properties:    Properties;
    text_pt:       string;
    place_name_pt: string;
    text:          string;
    place_name:    string;
    center:        number[];
    geometry:      Geometry;
    context:       Context[];
}

export interface Context {
    id:           string;
    mapbox_id:    string;
    text_pt:      string;
    text:         string;
    wikidata?:    Wikidata;
    language_pt?: Language;
    language?:    Language;
    short_code?:  ShortCode;
}

export enum Language {
    Pt = "pt",
}

export enum ShortCode {
    Br = "br",
    BrSc = "BR-SC",
}

export enum Wikidata {
    Q155 = "Q155",
    Q155557 = "Q155557",
    Q41115 = "Q41115",
}

export interface Geometry {
    coordinates: number[];
    type:        string;
}

export interface Properties {
    foursquare: string;
    landmark:   boolean;
    address:    string;
    category:   string;
    maki?:      string;
}
